name: Playwright Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - name: Install dependencies
              run: npm install -g pnpm && pnpm install
              
            # Add caching to speed up workflow
            - name: Cache pnpm modules
              uses: actions/cache@v3
              with:
                path: ~/.pnpm-store
                key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-
                  
            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps
              
            - name: Run Playwright tests
              run: pnpm exec playwright test --project=chromium-ui
              
            # Add reporting artifacts
            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 7
